=== andreaskasper/wsdc/xml/schemas/event.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- bearbeitet mit XMLSpy v2025 (x64) (https://www.altova.com) von Andreas Kasper (goo1) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="eventCollection">
		<xs:annotation>
			<xs:documentation>A festival, danceevent or competitionevent</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="event" type="eventType"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="eventType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="location" type="locationType" minOccurs="0"/>
			<xs:element name="competition" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="locationType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="address" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="street" minOccurs="0"/>
						<xs:element name="postal-code" minOccurs="0"/>
						<xs:element name="city" minOccurs="0"/>
						<xs:element name="state" minOccurs="0"/>
						<xs:element name="country" minOccurs="0"/>
						<xs:element name="coordinates" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="latitude" type="xs:float"/>
									<xs:element name="longitude" type="xs:float"/>
									<xs:element name="altitude" type="xs:float" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="phone" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="type" type="xs:string"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== andreaskasper/wsdc/xml/schemas/example_event.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<eventCollection xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/andreaskasper/wsdc/refs/heads/main/xml/schemas/event.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="v0.1">
  <event>
    <name>Testevent</name>
    <location type="venue">
      <name>D-TownSwing 2024</name>
      <address />
      <phone>string</phone>
      <phone>string</phone>
      <phone>string</phone>
    </location>
    <location type="hotel">
      <name>The Niu DÃ¼sseldorf</name>
      <address />
      <phone>string</phone>
    </location>
    <competition />
    <competition />
    <competition />
  </event>
</eventCollection>
